services:
  - type: web
    name: thsr-line-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
      - key: PORT
        value: "10000"
